### ISSUE TITLE
Import and export schedule

### ISSUE THREAD

**Issue by kiko-g** [NIAEFEUP/tts-revamp-fe#81]
**Overview** :
Create a interface that makes it possible to export and import specific schedules via string

**Tasks** :
- [x] Create the logic to generate a link with the information about the schedule
- [x] Create the Copy Buttom to copy the link (export the schedule)
- [x] Create the Text Input + Load Buttom to import the link and change the schedule
- [ ] Logic to change the schedule with the import
- [ ] Warning/Confirmation Modal to let the user know it is importing a schedule that is not compatible with the current curricular units selected
